Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
public_tweets = api.home_timeline()
for tweet in public_tweets:
    print(tweet.text)
------------------

[0;31m[0m
[0;31mTweepError[0mTraceback (most recent call last)
[0;32m<ipython-input-4-3248a1addfc9>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mpublic_tweets[0m [0;34m=[0m [0mapi[0m[0;34m.[0m[0mhome_timeline[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfor[0m [0mtweet[0m [0;32min[0m [0mpublic_tweets[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mprint[0m[0;34m([0m[0mtweet[0m[0;34m.[0m[0mtext[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/tweepy/binder.py[0m in [0;36m_call[0;34m(*args, **kwargs)[0m
[1;32m    251[0m                 [0;32mreturn[0m [0mmethod[0m[0;34m[0m[0;34m[0m[0m
[1;32m    252[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 253[0;31m                 [0;32mreturn[0m [0mmethod[0m[0;34m.[0m[0mexecute[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    254[0m         [0;32mfinally[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    255[0m             [0mmethod[0m[0;34m.[0m[0msession[0m[0;34m.[0m[0mclose[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/tweepy/binder.py[0m in [0;36mexecute[0;34m(self)[0m
[1;32m    232[0m                     [0;32mraise[0m [0mRateLimitError[0m[0;34m([0m[0merror_msg[0m[0;34m,[0m [0mresp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    233[0m                 [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 234[0;31m                     [0;32mraise[0m [0mTweepError[0m[0;34m([0m[0merror_msg[0m[0;34m,[0m [0mresp[0m[0;34m,[0m [0mapi_code[0m[0;34m=[0m[0mapi_error_code[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    235[0m [0;34m[0m[0m
[1;32m    236[0m             [0;31m# Parse the response payload[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mTweepError[0m: [{'code': 89, 'message': 'Invalid or expired token.'}]
TweepError: [{'code': 89, 'message': 'Invalid or expired token.'}]

